# Check out this great guide to environment files!
# https://carpentries-incubator.github.io/introduction-to-conda-for-data-scientists/04-sharing-environments/index.html

name: TSEmbed

# higher channels get priority
channels:
  - conda-forge
  - anaconda
  - defaults

# Prefer conda dependencies over pip wherever possible
dependencies:
  - pandas
  - numpy
  - matplotlib
  - optuna
  - scikit-learn
  - pywt
  - scipy
  - fastdtw
  - tensorflow
  - kerashypetune
  - gtda
  - umap-learn
  - networkx
  - ts2vg
  - gudhi

variables:
  CACHE_NUMBER: 0
